NomicFoundation/edr

- .changeset/new-coins-eat.md
- .changeset/tough-students-compare.md
- .changeset/two-suits-admire.md
- Cargo.lock
- crates/edr_evm/Cargo.toml
- crates/edr_evm/src/collections/shared_map.rs
- crates/edr_evm/src/state/trie.rs
- crates/edr_evm/src/state/trie/account.rs
- crates/edr_evm/src/state/trie/persistent_memory_db.rs
- crates/edr_evm/src/state/trie/state_trie.rs
- crates/edr_evm/src/state/trie/storage_trie.rs
- crates/edr_evm/src/state/trie/trie_query.rs
- crates/edr_provider/Cargo.toml
- crates/edr_provider/src/data.rs
- crates/edr_provider/src/debug_mine.rs
- crates/edr_provider/src/requests/eth/transactions.rs
- crates/edr_provider/src/snapshot.rs
- crates/tools/Cargo.toml
- crates/tools/js/benchmark/index.js
- crates/tools/src/main.rs
This re-applies the commits added by @agostbiro after I started migrating the repo. Specifically:
- https://github.com/NomicFoundation/hardhat/commit/dc6840c31445398a876813abcda8ba8e5a5796cb
- https://github.com/NomicFoundation/hardhat/commit/e6665a5e5202338927ade88a442e15c01e6c812e
- https://github.com/NomicFoundation/hardhat/commit/abb63166e8cff9545426e9447da3c2637c59dfd9
- And just the EDR side of https://github.com/NomicFoundation/hardhat/commit/6447e809b00fa13348c097080deb4042ad7453b1
> Reapply agost changes

- crates/edr_napi/npm/darwin-arm64/package.json
- crates/edr_napi/npm/darwin-x64/package.json
- crates/edr_napi/npm/linux-arm64-gnu/package.json
- crates/edr_napi/npm/linux-arm64-musl/package.json
- crates/edr_napi/npm/linux-x64-gnu/package.json
- crates/edr_napi/npm/linux-x64-musl/package.json
- crates/edr_napi/npm/win32-x64-msvc/package.json
- crates/edr_napi/package.json
Having the wrong repositories caused the release process to fail: https://github.com/NomicFoundation/edr/actions/runs/8876438556/job/24368408810
> Update repository in package.json files

- .changeset/serious-adults-smash.md
- crates/edr_eth/src/remote/eth/call_request.rs
- crates/edr_eth/src/transaction.rs
> feat: support input as alias in eth_call and eth_sendTransaction

- hardhat-tests/test/internal/hardhat-network/stack-traces/compilation.ts
Taken from https://github.com/NomicFoundation/hardhat/commit/1a333992af663e09873cd6ce4d4330d0fa900af0
> Use native compilers for stack traces tests

- Cargo.lock
- crates/edr_provider/Cargo.toml
- crates/edr_provider/src/data.rs
Follow up from https://github.com/NomicFoundation/edr/pull/446 to close https://github.com/NomicFoundation/edr/issues/445.
> misc: use Cargo version of `alloy-dyn-abi`

- .github/workflows/edr-benchmark.yml
- crates/tools/js/benchmark/package.json
- crates/tools/js/benchmark/test/test-local-edr.js
- hardhat-tests/integration/smock/package.json
- pnpm-lock.yaml
Test that we're using a local EDR package before running benchmarks in CI.
> ci: test using local edr package for benchmark

- hardhat-tests/test/internal/hardhat-network/stack-traces/test.ts
I was re-visiting the stack traces test runner and noticed some minor things that could be improved. Nothing here is necessary, but it doesn't hurt.
I recommend reviewing this commit by commit.
> Stack traces test runner improvements

- book/src/02_development/05_pnpm_link.md
- book/src/SUMMARY.md
> docs: add pnpm link instructions

- .github/workflows/mdbook.yml
The CI is failing in main because of this. I'm not sure why this wasn't caught in the PR.
> chore: run prettier

- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/call-message/multiple-modifiers-require/c.sol
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/call-message/multiple-modifiers-require/test.json
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/create-message/multiple-modifiers-require/c.sol
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/create-message/multiple-modifiers-require/test.json
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/between-statements/c.sol
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/between-statements/test.json
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/no-other-statements/c.sol
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/no-other-statements/test.json
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/statement-after/c.sol
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/statement-after/test.json
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/statement-before/c.sol
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/statement-before/test.json
Re-applying the changes from https://github.com/NomicFoundation/hardhat/pull/5467
See discussion in https://github.com/NomicFoundation/hardhat/issues/5443
> test: avoid unconditional reverts in stack traces tests

- .github/workflows/hardhat-tests.yml
See https://github.com/NomicFoundation/hardhat/pull/5478 for an explanation.
> ci: enable some debug logs for hardhat tests

- .changeset/wild-phones-drum.md
- Cargo.lock
- crates/edr_eth/Cargo.toml
- crates/edr_eth/src/transaction/signed/eip155.rs
- crates/edr_eth/src/transaction/signed/eip1559.rs
- crates/edr_eth/src/transaction/signed/eip2930.rs
- crates/edr_eth/src/transaction/signed/eip4844.rs
- crates/edr_eth/src/transaction/signed/legacy.rs
- crates/edr_evm/Cargo.toml
- crates/edr_evm/src/block/builder.rs
- crates/edr_evm/src/debug_trace.rs
- crates/edr_evm/src/state/diff.rs
- crates/edr_evm/src/state/trie/storage_trie.rs
- crates/edr_evm/src/trace.rs
- crates/edr_evm/src/transaction.rs
- crates/edr_napi/src/result.rs
- crates/edr_provider/Cargo.toml
- crates/edr_provider/src/data.rs
- crates/edr_provider/src/error.rs
This was my process for these changes:
- Take https://github.com/NomicFoundation/edr/commit/2ccd443f88fa5f8f26b54c28a9a4a274490cf30e
- Modify the `Cargo.toml` files like in that commit (but without using the forks)
- `cargo build`
- Fix errors and warnings with a combination of stealing things from that commit, guesswork, and luck
- ???
- This PR
> feat: upgrade revm dependencies

- Cargo.lock
- crates/edr_eth/Cargo.toml
- crates/edr_eth/src/chain_spec.rs
- crates/edr_eth/src/eips/eip1559.rs
- crates/edr_eth/src/receipt.rs
- crates/edr_eth/src/receipt/execution.rs
- crates/edr_eth/src/receipt/transaction.rs
- crates/edr_evm/Cargo.toml
- crates/edr_evm/src/block/builder.rs
- crates/edr_evm/src/chain_spec.rs
- crates/edr_evm/src/debug.rs
- crates/edr_evm/src/debug_trace.rs
- crates/edr_evm/src/miner.rs
- crates/edr_evm/src/precompiles.rs
- crates/edr_evm/src/runtime.rs
- crates/edr_evm/src/test_utils.rs
- crates/edr_evm/src/trace.rs
- crates/edr_evm/src/transaction.rs
- crates/edr_optimism/Cargo.toml
- crates/edr_optimism/src/receipt/execution.rs
- crates/edr_optimism/src/spec.rs
- crates/edr_provider/Cargo.toml
- crates/edr_provider/src/data.rs
- crates/edr_provider/src/data/call.rs
- crates/edr_provider/src/data/gas.rs
- crates/edr_provider/src/requests/eth/transactions.rs
This incorporates Dragan's changes to my REVM PR
> bump: revm with upstream changes

- crates/foundry/testdata/default/fork/LaunchFork.t.sol
Copied from https://github.com/foundry-rs/foundry/pull/8593
> test: fix deposit WETH test

- crates/edr_napi/src/trace/contracts_identifier.rs
- crates/edr_napi/src/trace/error_inferrer.rs
This PR is just meant to illustrate the issues. I'm sure there are more idiomatic ways to fix these things; feel free to close this PR and open a different one with better fixes.
> Fixes after testing in OZ

- Cargo.lock
- Cargo.toml
- crates/foundry/cheatcodes/src/inspector.rs
- crates/foundry/cheatcodes/src/lib.rs
- crates/foundry/evm/core/src/backend/mod.rs
- crates/foundry/evm/core/src/utils.rs
- crates/foundry/evm/evm/src/executors/mod.rs
- crates/foundry/evm/evm/src/inspectors/stack.rs
As it says on the tin. Based on https://github.com/foundry-rs/foundry/pull/8220
> chore(deps): bump revm 10.0, un-git revm-inspectors

- crates/edr_solidity_tests/tests/testdata/default/cheats/GetCode.t.sol
- crates/edr_solidity_tests/tests/testdata/default/cheats/ProjectRoot.t.sol
- crates/foundry/cheatcodes/src/fs.rs
Fix cheatcode tests where regressions kept in.
> chore: fix cheatcode tests

- Cargo.lock
- crates/edr_solidity_tests/src/gas_report.rs
- crates/edr_solidity_tests/src/multi_runner.rs
- crates/edr_solidity_tests/src/runner.rs
- crates/edr_solidity_tests/tests/it/helpers/config.rs
- crates/edr_solidity_tests/tests/it/repros.rs
- crates/foundry/evm/evm/src/executors/invariant/replay.rs
- crates/foundry/evm/traces/Cargo.toml
- crates/foundry/evm/traces/src/abi.rs
- crates/foundry/evm/traces/src/decoder/mod.rs
- crates/foundry/evm/traces/src/decoder/precompiles.rs
- crates/foundry/evm/traces/src/lib.rs
Based on https://github.com/foundry-rs/foundry/pull/8224
> chore: delegate trace formatting to `revm-inspectors`

- .changeset/polite-plums-ring.md
- crates/edr_napi/index.d.ts
- crates/edr_napi/src/trace/exit.rs
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/special-cases/precompile-failure/c.sol
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/special-cases/precompile-failure/test.json
> fix: don't panic when a precompile errors

- .github/workflows/edr-benchmark.yml
- .github/workflows/edr-ci.yml
- .github/workflows/edr-npm-release.yml
- .github/workflows/hardhat-tests.yml
- .github/workflows/test-recent-mainnet-block.yml
Update checkout and cache actions. Fixes #784.
> Update checkout and cache actions

- .changeset/rich-parents-shave.md
- crates/edr_napi/test/issues.ts
- crates/edr_provider/src/interval.rs
- hardhat-tests/package.json
- hardhat-tests/test/internal/hardhat-network/stack-traces/execution.ts
- hardhat-tests/test/internal/hardhat-network/stack-traces/test.ts
- patches/hardhat@2.22.17.patch
- pnpm-lock.yaml
> fix: issue 771

- crates/edr_napi/npm/darwin-arm64/package.json
- crates/edr_napi/npm/darwin-x64/package.json
- crates/edr_napi/npm/linux-arm64-gnu/package.json
- crates/edr_napi/npm/linux-arm64-musl/package.json
- crates/edr_napi/npm/linux-x64-gnu/package.json
- crates/edr_napi/npm/linux-x64-musl/package.json
- crates/edr_napi/npm/win32-x64-msvc/package.json
> edr-0.8.0-alpha.1

- .changeset/good-pears-draw.md
- crates/edr_eth/src/block.rs
- crates/edr_eth/src/block/options.rs
- crates/edr_evm/src/block.rs
- crates/edr_evm/src/block/remote.rs
- crates/edr_napi/src/block.rs
- crates/edr_provider/src/requests/eth/blocks.rs
- crates/edr_rpc_eth/src/block.rs
Resolves #813.
I added a [follow-up task](https://github.com/NomicFoundation/edr/issues/812) for once a Prague block has been generated on Holesky.
> feat: add EIP-7685 properties to block header

- .changeset/good-pears-draw.md
- crates/edr_eth/src/lib.rs
- crates/edr_napi/index.d.ts
- crates/edr_provider/tests/common/blob.rs
- crates/edr_provider/tests/common/mod.rs
- crates/edr_provider/tests/eip4844.rs
- crates/edr_provider/tests/integration/eip7691.rs
- crates/edr_provider/tests/integration/mod.rs
> test: add test for EIP-7691

- crates/edr_provider/tests/integration/eip7623.rs
- crates/edr_provider/tests/integration/eip7623/deploy_contract.rs
- crates/edr_provider/tests/integration/eip7623/send_data_to_eoa.rs
- crates/edr_provider/tests/integration/mod.rs
> test: add tests for EIP-7623

- crates/foundry/evm/core/src/opts.rs
I noticed that we're logging the fork url in Solidity tests if we fail to create the fork. This is problematic, because the url can contain api keys.
> fix: don't log fork url on error

- crates/edr_eth/src/block.rs
- crates/edr_eth/src/eips/eip4844.rs
- crates/edr_eth/src/transaction.rs
- crates/edr_eth/src/transaction/signed/eip7702.rs
- crates/edr_evm/src/eips/eip2935.rs
- crates/edr_evm/tests/integration/eip2935.rs
This PR fixes several issues that were missed when porting Prague support to the multichain branch, due to broken CI.
> fix: EIP-7702 port

- crates/tools/js/benchmark/src/index.ts
- crates/tools/js/benchmark/src/solidity-tests.ts
Adapts the Solidity test benchmark runner to allow running Solidity tests in any Hardhat v3 project. Useful for debugging and profiling.
> misc: run soltests in hh3 projects

- Cargo.lock
- Cargo.toml
- crates/edr_eth/Cargo.toml
- crates/edr_eth/src/transaction/pooled.rs
- crates/edr_eth/src/transaction/pooled/eip4844.rs
- crates/edr_evm/Cargo.toml
- crates/edr_evm/src/interpreter.rs
- crates/edr_evm/src/precompile.rs
- crates/edr_evm/src/runtime.rs
- crates/edr_evm/src/test_utils.rs
- crates/edr_evm/tests/integration/blockchain.rs
- crates/edr_evm/tests/integration/issues.rs
- crates/edr_evm/tests/integration/op.rs
- crates/edr_generic/Cargo.toml
- crates/edr_generic/tests/integration/unknown_transaction_type.rs
- crates/edr_op/Cargo.toml
- crates/edr_op/src/receipt/block.rs
- crates/edr_op/src/receipt/factory.rs
- crates/edr_op/src/rpc.rs
- crates/edr_op/tests/integration/rpc.rs
- crates/edr_provider/Cargo.toml
- crates/edr_provider/src/data.rs
- crates/edr_provider/src/requests/eth/call.rs
- crates/edr_provider/src/requests/eth/gas.rs
- crates/edr_provider/tests/common/blob.rs
- crates/edr_rpc_eth/Cargo.toml
- crates/edr_rpc_eth/src/receipt.rs
- crates/edr_scenarios/Cargo.toml
> build: upgrade to REVM v21

- .github/workflows/test-recent-optimism-block.yml
[ref](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#masking-a-value-in-a-log)
> chore: mask workflow variable

- .changeset/giant-spoons-notice.md
- crates/edr_evm/src/hardfork/l1.rs
- crates/edr_op/src/hardfork/base.rs
- crates/edr_op/src/hardfork/op.rs
- crates/edr_op/tests/integration/hardfork_activation.rs
- hardhat-tests/test/internal/hardhat-network/provider/hardhat-network-options.ts
Activations are based on:
- https://blog.ethereum.org/2025/02/14/pectra-testnet-announcement
- https://blog.ethereum.org/2025/03/18/hoodi-holesky
- https://blog.ethereum.org/2025/04/23/pectra-mainnet
- https://github.com/ethereum-optimism/superchain-registry/
> feat: add Prague hardfork activations

- crates/edr_evm/src/hardfork/l1.rs
Applying a [small suggestion](https://github.com/NomicFoundation/edr/pull/907#pullrequestreview-2835484585) by Copilot post-merge.
> chore: use named constants instead of literals

- crates/edr_macros/src/cheatcodes.rs
- crates/edr_solidity_tests/src/result.rs
- crates/edr_solidity_tests/src/runner.rs
- crates/edr_solidity_tests/tests/it/core.rs
- crates/edr_solidity_tests/tests/testdata/default/core/DeprecatedCheatcode.t.sol
- crates/foundry/cheatcodes/assets/cheatcodes.json
- crates/foundry/cheatcodes/assets/cheatcodes.schema.json
- crates/foundry/cheatcodes/spec/src/cheatcode.rs
- crates/foundry/cheatcodes/spec/src/vm.rs
- crates/foundry/cheatcodes/src/inspector.rs
- crates/foundry/cheatcodes/src/lib.rs
- crates/foundry/evm/evm/src/executors/fuzz/mod.rs
- crates/foundry/evm/evm/src/executors/fuzz/types.rs
- crates/foundry/evm/evm/src/executors/invariant/replay.rs
- crates/foundry/evm/fuzz/src/lib.rs
This PR backports https://github.com/foundry-rs/foundry/pull/8883. This is a prerequisite for backporting https://github.com/foundry-rs/foundry/pull/8945
> feat: add cheatcode deprecation warning

- Cargo.toml
These comments were introduced in #940. Confirmed with @agostbiro that they should be removed.
> chore: remove commented lines in Cargo.toml

- .github/codecov.yml
> chore: disable Codecov checks

- .changeset/spicy-cameras-fix.md
- crates/edr_solidity/src/error_inferrer.rs
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/call-message/modifier-private-method/c.sol
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/call-message/modifier-private-method/test.json
Cherry-picked https://github.com/NomicFoundation/edr/pull/957 for release in HH2
> fix: avoid panic on stack trace for receive with modifier (#957)

- book/src/01_getting_started/01_setup.md
- book/src/01_getting_started/03_test.md
I changed node JS version mentioned in `01_getting_started/01_setup.md` from 18 to 22 following what's configured in `devcontainer.json` file
> doc: update `getting_started` doc

- crates/edr_evm/src/trace.rs
A panic resulting from REVM's `FatalExternalError` was reported in https://github.com/NomicFoundation/edr/issues/1059. This PR improves the shown panic message.
> misc: improve EVM internal panic messages
