- crates/tools/js/benchmark/README.md
- crates/tools/js/benchmark/index.js
- crates/tools/js/benchmark/package.json
- pnpm-lock.yaml
Manually re-applying changes from https://github.com/NomicFoundation/hardhat/pull/5150
I tried cherry-picking them, but it was causing me a lot of issues, I'm not sure why.
> ci: add Anvil option to JS benchmark runner

- book/src/01_getting_started/05_profiling.md
Add instructions for profiling with perf/DTrace.
> docs: add instructions for profiling with perf/DTrace

- crates/edr_napi/CHANGELOG.md
I moved these changes over from an earlier PR that wasn't merged before the release
> style: create consistent changelog

- .changeset/old-crews-remain.md
- crates/edr_eth/src/remote/client.rs
> refactor: retry once when receiving some sporadic JSON-RPC errors

- .changeset/lovely-tables-impress.md
- Cargo.lock
- crates/edr_eth/Cargo.toml
- crates/edr_eth/src/block/difficulty.rs
- crates/edr_eth/src/block/reward.rs
- crates/edr_evm/Cargo.toml
- crates/edr_evm/benches/state/util.rs
- crates/edr_evm/src/debug_trace.rs
- crates/edr_evm/src/trace.rs
- crates/edr_evm/src/transaction/executable.rs
- crates/edr_napi/src/trace.rs
- crates/edr_provider/src/console_log.rs
- crates/edr_provider/src/mock.rs
I'm okay waiting to merge this until after benchmarks are re-enabled. I'm curious to see whether performance is at all affected by changes in `revm`
> build: bump revm to commit aceb093

- .github/workflows/edr-benchmark.yml
Don't cancel in progress benchmark jobs in main.
> ci: don't cancel in progress benchmark jobs in main

- .github/workflows/edr-npm-release.yml
This should let us make pre-releases both from `main` and from the `prerelease` branch. Production releases can only be done from `main` now.
I removed the code related to the `edr/release` branch since we are not using it anymore; that was a leftover from when we were working on the Hardhat repo.
> Allow pre-releases from the prerelease branch

- .changeset/young-pans-help.md
- .github/workflows/edr-npm-release.yml
- crates/edr_napi/npm/darwin-arm64/package.json
- crates/edr_napi/npm/darwin-x64/package.json
- crates/edr_napi/npm/linux-arm64-gnu/package.json
- crates/edr_napi/npm/linux-arm64-musl/package.json
- crates/edr_napi/npm/linux-x64-gnu/package.json
- crates/edr_napi/npm/linux-x64-musl/package.json
- crates/edr_napi/npm/win32-x64-msvc/package.json
- crates/edr_napi/package.json
- crates/edr_napi/scripts/prepublish.sh
Hardhat users are frequently running into https://github.com/npm/cli/issues/4828. As a blunt workaround, we are going to turn all the builds into dependencies of the entry-point package `@nomicfoundation/edr`, instead of being optional dependencies. For this to work, two things have to happen:
1. The `package.json` of EDR has to use them as plain `dependencies` instead of `optionalDependencies`
2. The `package.json`s of the builds don't have to include things like `os` and `arch`, because the package manager might check them and complain if they don't match.
Since the `optionalDependencies` field of the entry-point package.json are added/modified by the NAPI-RS CLI, the only way to deal with 1 is to modify the `package.json` after running `napi prepublish`. This is done with `jq` and …
> Include all builds as normal dependencies

- .changeset/curly-carpets-join.md
We are going to use minor versions only for breaking changes. Shipping new features in 0.x with patch versions increases the amount of users that receive this change.
> Use patch bump for blob txs support

- .github/workflows/release.yml
I find it super confusing to have an "EDR npm release" and a "Release" workflow and I never remember what the second one is about. I renamed it to make it more clear.
> Rename changesets PR

- .changeset/neat-keys-promise.md
- crates/edr_provider/src/lib.rs
- crates/edr_provider/src/requests/methods.rs
- crates/edr_provider/tests/eth_request_serialization.rs
eth_sign was implemented as an alias of personal_sign. This was not correct, as the order of the parameters is different for both methods.
Closes https://github.com/NomicFoundation/edr/issues/455
> Fix eth_sign parameters order

- Cargo.toml
- crates/edr_napi/Cargo.toml
- crates/edr_napi/package.json
- hardhat-tests/package.json
We build `edr_napi` for JS tests with the release profile for speedy execution. As part of forking Foundry for Solidity tests we adopted their release flags. This significantly increased the running time of tests which is annoying for local development.
This change fixes that by adopting a custom publish release profile for `edr_napi`. I took the approach of opting out of this profile for tests to ensure that no release can be published by accident with inferior optimizations.
> ci: custom publish release profile for `edr_napi`

- .github/workflows/edr-ci.yml
- crates/edr_napi/CHANGELOG.md
- package.json
- pnpm-lock.yaml
This PR changes the CI so that prettier is run using a script from the root's package.json. This makes it easier to guarantee that we are using the same version and config locally and in the CI, and means depending on one less external GH action.
> Fix prettier

- .github/workflows/review-requested-slack-notification.yml
- .github/workflows/review-submitted-slack-notification.yml
These workflows will notify us on Slack when a PR review is requested or submitted. They use the jobs defined here: https://github.com/NomicFoundation/github-actions-workflows/tree/main/.github/workflows
> ci: add workflows for PR reviews slack notifications

- crates/edr_eth/src/transaction.rs
- crates/edr_eth/src/transaction/signed.rs
- crates/edr_evm/src/block.rs
- crates/edr_evm/src/block/builder.rs
- crates/edr_evm/src/block/local.rs
- crates/edr_evm/src/block/remote.rs
- crates/edr_evm/src/chain_spec.rs
- crates/edr_evm/src/debug_trace.rs
- crates/edr_evm/src/lib.rs
- crates/edr_evm/src/mempool.rs
- crates/edr_evm/src/miner.rs
- crates/edr_evm/src/test_utils.rs
- crates/edr_evm/src/transaction/detailed.rs
- crates/edr_evm/src/transaction/executable.rs
- crates/edr_evm/tests/blockchain.rs
- crates/edr_napi/src/logger.rs
- crates/edr_provider/src/data.rs
- crates/edr_provider/src/logger.rs
- crates/edr_provider/src/requests/eth/call.rs
- crates/edr_provider/src/requests/eth/gas.rs
- crates/edr_provider/src/requests/eth/transactions.rs
- crates/edr_provider/src/requests/validation.rs
- crates/edr_provider/tests/eip4844.rs
This PR is intended as an incremental change towards chain-specific blockchains. In particular, it adds a generic trait bound to `ExecutableTransaction`. For now, we always use the `L1ChainSpec` at compile-time.
> refactor: add generic trait bound to ExecutableTransaction

- crates/edr_evm/tests/issues.rs
- I added `hh` to the issue that comes from Hardhat. Right now it's obvious that a 4-digit issue is from Hardhat and a 3-digit one is from the EDR repo, but that can be confusing in the future.
- One of the Hardhat issues was moved to the EDR repo, so its number changed.
- I added descriptions to the names besides just having the issue numbers. We should probably do that in `edr_provider/tests/issues` too, but I didn't want to put time into that right now.
> test: rename edr_evm issues tests

- .changeset/fair-rice-vanish.md
- crates/edr_provider/src/lib.rs
- crates/edr_provider/src/requests.rs
- crates/edr_provider/src/requests/eth/evm.rs
- crates/edr_provider/src/requests/methods.rs
- crates/edr_provider/src/requests/serde.rs
- crates/edr_provider/tests/eth_request_serialization.rs
- crates/edr_provider/tests/timestamp.rs
- hardhat-tests/test/internal/hardhat-network/provider/modules/evm.ts
Fixes #435 
In place of the existing `U64OrUsize` we provide a newtype `Timestamp` around `u64` with a custom Deserialize impl that leniently first deserializes to a number/string and then attempts to parse the value to see if it's within the valid range.
We keep providing `From` and `Into` for the new type, so the existing code keeps using the impls whenever possible.
> refactor: Provide helpful error msg when deserializing big timestamp

- .github/workflows/edr-benchmark.yml
- .github/workflows/edr-ci.yml
- .github/workflows/edr-npm-release.yml
- .github/workflows/hardhat-tests.yml
- .github/workflows/release.yml
- package.json
- pnpm-lock.yaml
Moving to pnpm 9 to align with Hardhat and Ignition.
If you use [volta](https://volta.sh/), then doing `volta install pnpm@9` should be enough to migrate. I'm not sure about other installation methods.
> chore: use pnpm v9

- .changeset/twelve-yaks-unite.md
- crates/edr_evm/src/state/remote/cached.rs
- crates/edr_provider/tests/issues/issue_503.rs
- crates/edr_provider/tests/issues/mod.rs
Fixes https://github.com/NomicFoundation/edr/issues/503
> fix: split code from remote account in

- .changeset/modern-ways-wash.md
- crates/edr_evm/src/block/remote.rs
See https://github.com/NomicFoundation/hardhat/discussions/5266#discussioncomment-9776377
I didn't add a test for this because neither Infura nor Alchemy support that creditcoin chain, and I don't think we should use public RPC URLs in our tests, since they don't tend to be very robust.
> fix: accept missing mix hashes in remote blocks

- crates/edr_evm/src/blockchain.rs
- crates/edr_evm/src/blockchain/forked.rs
This error is a bit better if it includes the remote chain id, because then adding it to the default hardfork histories (as done in https://github.com/NomicFoundation/hardhat/pull/5394) will be easier.
> improvement: add chain id to error message

- .github/workflows/edr-npm-release.yml
The main change here is a couple of new steps, checking that the number of build jobs and the number of unique generated artifacts are the ones we expect.
There surely are better ways to do this, but this seems like a simple way to get it done. These are the relevant changes:
- Added a workflow-scoped `NUMBER_OF_TARGETS` variable. Its current value is 7.
- Added a check that the number of build jobs matches that number.
- Added a check that the number of _unique_ generated artifacts is the expected one.
The last item is the one that catches the problem we had before. I double checked this by temporarily setting the OSes to `macos-latest` again. This generated 6 unique artifacts, and was caught by that step.
I included two unrelated changes here, fixing some things I noticed while working …
> ci: make release workflow more robust

- crates/edr_napi/index.d.ts
- crates/edr_napi/src/solidity_tests.rs
- crates/edr_napi/src/solidity_tests/runner.rs
- crates/edr_napi/test/solidity-tests.ts
- crates/tools/js/benchmark/.gitignore
- crates/tools/js/benchmark/index.js
- crates/tools/js/benchmark/package.json
- crates/tools/js/benchmark/solidity-tests.js
- pnpm-lock.yaml
Adds a JS benchmark command to execute certain `forge-std` tests to benchmark the EDR Solidity tests implementation against `forge`. The benchmark can be executed with `pnpm i && pnpm soltests` from the `crates/tools/js/benchmark` directory. There is no difference in execution time on my machine between `forge test` and `pnpm soltests`.
Baseline: 
```
git clone https://github.com/NomicFoundation/forge-std.git
cd forge-std
git checkout js-benchmark-config
foundryup --commit 0a5b22f07
forge test --no-match-contract 'StdChainsTest|StdCheatsTest|MockERC721Test|MockERC20Test|StdCheatsForkTest|StdJsonTest|StdUtilsForkTest|StdTomlTest'
```
The ignored `forge-std` tests use fork mode or depend on Foundry project format.
> Add Solidity tests JS benchmark

- .changeset/big-boxes-drop.md
- crates/edr_evm/src/block/remote.rs
Resolved https://github.com/NomicFoundation/edr/issues/536
> fix: allow missing nonce in remote blocks

- .github/workflows/edr-benchmark.yml
- .github/workflows/edr-ci.yml
- .github/workflows/edr-npm-release.yml
- .github/workflows/hardhat-tests.yml
- .github/workflows/release.yml
This version of pnpm/action-setup stopped working today for some reason. Upgrading to v4 seems to fix it.
> ci: upgrade pnpm/action-setup

- .github/workflows/edr-benchmark.yml
These path restrictions made sense when EDR was part of the Hardhat repo, but they can cause problems now that the EDR has its own repo (e.g. they wouldn't run if the Hardhat version was changed).
> ci: remove path checks for benchmarks

- .github/workflows/edr-ci.yml
Check that `index.d.ts` has no changes after running `pnpm build`.
The failing job should start working after https://github.com/NomicFoundation/edr/pull/552 is merged.
> ci: check that index.d.ts is up to date

- crates/edr_napi/src/solidity_tests.rs
Added an assertion to check that scheduling Solidity tests progress callback succeeded. This should always succeed since we're using an unbounded queue. Only adding the assertion for completeness, it's not strictly needed.
> refactor: assert scheduling callback succeeded

- .changeset/thick-impalas-sparkle.md
- Cargo.lock
- crates/edr_eth/Cargo.toml
- crates/edr_evm/Cargo.toml
- crates/edr_provider/Cargo.toml
- hardhat-tests/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
This voids the need for a fork on `main`.
> build: upgrade revm to v12

- crates/edr_napi/src/solidity_tests/config.rs
- crates/edr_napi/src/solidity_tests/runner.rs
- crates/foundry/cheatcodes/src/config.rs
- crates/foundry/cheatcodes/src/fs.rs
- crates/foundry/cheatcodes/src/utils.rs
- crates/foundry/forge/src/multi_runner.rs
- crates/foundry/forge/tests/it/repros.rs
I've decided to split this out from a larger change coming to remove the dependence of the Solidity test runner on the Foundry project format for https://github.com/NomicFoundation/edr/issues/487
> refactor: remove `ProjectPathsConfig` from `MultiContractRunner`

- crates/edr_napi/index.d.ts
- crates/edr_napi/index.js
- crates/edr_napi/src/solidity_tests.rs
- crates/edr_napi/test/solidity-tests.ts
- crates/foundry/forge/src/multi_runner.rs
- crates/tools/js/benchmark/solidity-tests.js
- hardhat-solidity-tests/src/index.ts
The Solidity test runner interface that is exposed from Rust looks like this currently (config options are WIP):
```tsx
/** Executes solidity tests. */
export class SolidityTestRunner {
/**Creates a new instance of the SolidityTestRunner. The callback function will be called with suite results as they finish. */
constructor(gasReport: boolean, resultsCallback: (SuiteResult) => void)
/**Runs the given test suites. */
runTests(testSuites: Array<TestSuite>): Promise<Array<SuiteResult>>
}
```
The `SolidityTestRunner`  makes no guarantees about when the progress callbacks are called. The only guarantee is that the callback will be scheduled to be called for each test suite as soon as the test suite finished executing. The scheduling is done by the NodeJS event loop and it can happen after the …
> refactor: Solidity test runner progress callback completion

- .changeset/fast-kings-search.md
- crates/edr_evm/src/blockchain.rs
- crates/edr_evm/src/blockchain/forked.rs
- crates/edr_provider/src/data.rs
- crates/edr_provider/src/requests/eth/call.rs
- crates/edr_provider/tests/issues/issue_533.rs
- crates/edr_provider/tests/issues/mod.rs
Use the remote chain id when simulating transactions in pre-fork blocks instead of the locally overridden one. Fixes #533
> fix: use remote chain id for pre-fork simulation

- crates/edr_napi/index.d.ts
- crates/edr_napi/index.js
- crates/edr_napi/src/trace.rs
- crates/edr_napi/src/trace/compiler.rs
- crates/edr_napi/src/trace/contracts_identifier.rs
- crates/edr_napi/src/trace/message_trace.rs
- crates/edr_napi/src/trace/model.rs
- crates/edr_napi/src/trace/vm_trace_decoder.rs
- crates/edr_napi/src/trace/vm_tracer.rs
- crates/edr_solidity/src/artifacts.rs
- hardhat-tests/test/internal/hardhat-network/stack-traces/test.ts
- patches/gen-hardhat-patches.sh
- patches/hardhat@2.22.6.patch
- pnpm-lock.yaml
This ports of `VmTraceDecoder` from Hardhat; what's left now is the error inferrer and finally solidity stack trace logic :partying_face: 
What's more interesting, however, is the fix for the `MessageTrace` and others:
1. There's a `napi-rs` bug that incorrectly validates and converts an object that has a required property but can be explicitly undefined, e.g. `deployedContract: Bytecode | undefined`. That's the case for `CreateMessageTrace` and so this is worked around using an optional property, however...
2. With this, the `CallMessageTrace` is a strict superset of `CreateMessageTrace`. We need to be careful with the type order when using the N-API type `Either` to always attempt converting and validating the most specific type first, otherwise we may incorrectly convert into a less …
> refactor: Port the `VmTraceDecoder` from Hardhat

- .changeset/two-starfishes-obey.md
- crates/edr_napi/index.d.ts
- crates/edr_napi/package.json
- crates/edr_napi/src/provider.rs
- crates/edr_napi/test/helpers.ts
- crates/edr_napi/test/issues.ts
- crates/edr_napi/test/provider.ts
- crates/tools/js/benchmark/index.js
- package.json
- patches/hardhat@2.22.7.patch
- pnpm-lock.yaml
> fix: prevent crash when returning large JSON responses

- crates/edr_napi/src/solidity_tests/config.rs
- crates/edr_napi/src/solidity_tests/runner.rs
- crates/foundry/common/src/evm.rs
- crates/foundry/config/README.md
- crates/foundry/config/src/lib.rs
- crates/foundry/evm/core/src/opts.rs
- crates/foundry/evm/traces/src/decoder/mod.rs
- crates/foundry/forge/src/multi_runner.rs
- crates/foundry/forge/tests/it/test_helpers.rs
- crates/foundry/testdata/foundry.toml
I broke out this change from a larger PR coming to expose Solidity test config options to JS through the ffi.
The [verbosity config](https://book.getfoundry.sh/reference/config/testing#verbosity) in Foundry controls the level of detail displayed to the user, but it's also used internally to determine what info to collect. Since displaying info to the user will be the responsibility of Hardhat, this PR removes the verbosity config and replaces it with a boolean flag whether to enable tracing. This is sufficient to preserve previous functionality.
> refactor: remove verbosity config

- hardhat-tests/.mocharc.json
- hardhat-tests/test/internal/hardhat-network/stack-traces/test.ts
It seems transpile-only transpiles per module, however we need to perform full "compilation" in order to correctly see and inline values for const enums.
We use const enums because that's how they are emitted by napi-rs and there's no option to change that. Rather than invest into supporting that or working around it, let's just fully compile the test harness once.
See https://www.typescriptlang.org/tsconfig/#isolatedModules for more context.
See https://github.com/NomicFoundation/edr/pull/589#discussion_r1710243142 for a comment on the original workaround.
> fix: Fully transpile in Mocha tests to correctly inline const enums

- Cargo.lock
- crates/edr_napi/Cargo.toml
- crates/edr_napi/index.d.ts
- crates/edr_napi/index.js
- crates/edr_napi/src/trace.rs
- crates/edr_napi/src/trace/compiler.rs
- crates/edr_napi/src/trace/error_inferrer.rs
- crates/edr_napi/src/trace/exit.rs
- crates/edr_napi/src/trace/mapped_inlined_internal_functions_heuristics.rs
- crates/edr_napi/src/trace/message_trace.rs
- crates/edr_napi/src/trace/model.rs
- crates/edr_napi/src/trace/opcodes.rs
- crates/edr_napi/src/trace/return_data.rs
- crates/edr_napi/src/trace/solidity_stack_trace.rs
- crates/edr_napi/src/trace/solidity_tracer.rs
- crates/edr_napi/src/trace/vm_trace_decoder.rs
- crates/edr_napi/src/utils.rs
- hardhat-tests/test/internal/hardhat-network/stack-traces/test.ts
- patches/gen-hardhat-patches.sh
- patches/hardhat@2.22.6.patch
- pnpm-lock.yaml
What says on the tin; this is the last meaningful piece of logic that was needed to be ported. What's remaining is the debug printing and then we can finally start cleaning up the JS cruft that we amassed during the porting.
I know I could be more succinct and polish it further but I figured that it's a 1:1 rewrite of these three files so one could compare them side-to-side and the time can be better spent finally tidying it all up :pray: 
This ports the most important three remaining files from Hardhat:
- https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/src/internal/hardhat-network/stack-traces/mapped-inlined-internal-functions-heuristics.ts
- https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/src/internal/hardhat-network/stack-traces/erro …
> refactor: Port ErrorInferrer and SolidityTracer from Hardhat

- crates/edr_napi/index.d.ts
- crates/edr_napi/index.js
- crates/edr_napi/src/trace.rs
- crates/edr_napi/src/trace/debug.rs
- crates/edr_napi/src/trace/model.rs
- crates/edr_napi/src/trace/opcodes.rs
- crates/edr_napi/src/trace/solidity_stack_trace.rs
- patches/gen-hardhat-patches.sh
- patches/hardhat@2.22.6.patch
- pnpm-lock.yaml
Based on #593
This re-implements the structured console.log printing from the original Hardhat.ts file. While not insanely useful on its own, it is the last file that references the underlying compiler model classes, and so this is the last brick that's necessary to cut and reduce the JS API exposure.
To test it, I modified the corresponding `test.ts` file in the Hardhat repo (using local EDR package link) to print both versions one after another (both message and stack traces) for select tests (It's useful to specify `"only": true"` and `"print": true` in the select `test.json` files). They're mostly the same with the exception of not bolding the JUMPs anymore but I didn't want to pull a new dependency for something so small.
To implement printing the entries as JSON in `printStackTrace` …
> refactor: Port stack-traces/debug.ts

- LICENSE
- crates/edr_napi/index.d.ts
- crates/edr_napi/index.js
- crates/edr_napi/src/solidity_tests.rs
- crates/edr_napi/src/solidity_tests/config.rs
- crates/edr_napi/src/solidity_tests/runner.rs
- crates/edr_napi/test/solidity-tests.ts
- crates/foundry/cheatcodes/src/config.rs
- crates/foundry/config/src/fuzz.rs
- crates/foundry/config/src/invariant.rs
- crates/tools/js/benchmark/solidity-tests.js
- hardhat-solidity-tests/src/index.ts
This PR exposes Solidity test runner config options to TypeScript from Rust through NAPI-RS.
The basis of the config options are the Foundry testing configuration options documented [here.](https://book.getfoundry.sh/reference/config/testing) There were some additional config options not covered there that are needed to construct a test runner. These are exposed based on the [Foundry config struct](https://github.com/NomicFoundation/edr/blob/103f3b12f73621867983cc58893ec5a8d212dc28/crates/foundry/config/src/lib.rs) that contains all configuration options (including build and deployment options which we don't need).
The following Foundry testing options are not exposed:
- [verbosity](https://book.getfoundry.sh/reference/config/testing#verbosity)
- This controls the CLI output verbosity …
> feat: solidity test runner config

- .changeset/empty-cars-join.md
- crates/edr_provider/src/data.rs
- crates/edr_provider/src/error.rs
- crates/edr_provider/tests/issues/issue_570.rs
- crates/edr_provider/tests/issues/mod.rs
- crates/edr_rpc_eth/src/lib.rs
- crates/edr_rpc_eth/src/transaction.rs
This PR resolves the following issues:
- https://github.com/NomicFoundation/edr/issues/597
- https://github.com/NomicFoundation/edr/issues/601
The approach taken is the one we discussed last Tuesday to fetch and filter transactions in the provider implementation of `debug_traceTransaction`. This is pretty hacky, but it has the advantage that changes are simple and localized and it'll be easy to remove once we have multi-chain support.
> fix: improve error message and option to skip unsupported transaction type in debug trace

- Cargo.lock
- crates/edr_napi/src/logger.rs
- crates/edr_optimism/Cargo.toml
- crates/edr_optimism/src/spec.rs
- crates/edr_optimism/src/transaction.rs
- crates/edr_optimism/src/transaction/pooled.rs
- crates/edr_optimism/src/transaction/request.rs
- crates/edr_optimism/src/transaction/signed.rs
- crates/edr_optimism/src/transaction/signed/deposit.rs
- crates/edr_provider/src/data.rs
- crates/edr_provider/src/error.rs
- crates/edr_provider/src/lib.rs
- crates/edr_provider/src/requests.rs
- crates/edr_provider/src/requests/eth/call.rs
- crates/edr_provider/src/requests/eth/gas.rs
- crates/edr_provider/src/requests/eth/transactions.rs
- crates/edr_provider/src/requests/validation.rs
- crates/edr_provider/src/spec.rs
This PR adds all required trait implementations to be able to use Optimism's chain spec for a provider.
> NOTE: To expedite exposing Optimism for testing in Hardhat, I didn't spend time on adding Optimism-specific provider tests yet.
> feat: Optimism provider

- crates/edr_napi/package.json
- pnpm-lock.yaml
See <https://github.com/napi-rs/napi-rs/pull/2088>
We encountered that in Slang - sometimes when you hop between branches and do rebuilds of `napi build` you get stale index.d.ts info due to cached typedefs between macro invocations. That's not guaranteed to work and backfires once you change the order of exports (e.g. changing the module structure, order etc.) as that gives duplicated type definitions.
The 2.18.4 also contains the missing `declare` attribute when exporting but I didn't pull that in to reduce churn across our feature branches; I assume that all of them modifies the index.d.ts substantially and so let's do that separately at our leisure.
> chore: Bump @napi-rs/cli to fix duplicated napi typedefs

- hardhat-tests/package.json
For some reason, stack traces test don't work when `edr_napi` is built with the debug profile. Since we were using the release profile before anyway, I think we can just continue using it to get this fixed.
> fix: build edr_napi with test profile when running hardhat tests

- crates/tools/js/benchmark/package.json
- hardhat-tests/integration/smock/package.json
- hardhat-tests/package.json
- package.json
- pnpm-lock.yaml
This removes the need for us to patch locally, so let's pull this in to clean up the patching for now.
> chore: Bump hardhat to 2.22.10

- .github/workflows/test-recent-mainnet-block.yml
- .github/workflows/test-recent-optimism-block.yml
- Cargo.lock
- crates/edr_evm/src/test_utils.rs
- crates/edr_optimism/tests/full_block.rs
- crates/edr_provider/src/data.rs
- crates/tools/Cargo.toml
- crates/tools/src/main.rs
- crates/tools/src/remote_block.rs
This PR adds support for replaying Optimism on-chain blocks to the CLI app and adds a GitHub workflow for nightly replays of the latest Optimism block.
This PR contains a breaking change to the CLI:
- `--chain-id` was removed as it can be retrieved from the remote
- `--chain-type` was added, replacing the meaning of `-c` from `--chain-id` to `--chain-type`
Once merged, this PR commit should be cherry-picked and applied to `main` to ensure that the `on.schedule` works.
> Scheduled workflows will only run on the default branch.
>
> https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
> ci: add workflow for testing Optimism every night

- .github/workflows/edr-ci.yml
This PR adds measuring of code coverage statistics while executing Rust tests and uploads the results to codecov.io
> ci: measure and upload code coverage

- crates/edr_evm/src/block.rs
- crates/edr_evm/src/chain_spec.rs
When I started implementing the `ChainSpec` trait I found it difficult to navigate all of the required traits, their associated types and how they all relate to each other.
Since the [book chapter](https://github.com/NomicFoundation/edr/blob/feat/multichain/book/src/04_multichain/01_chain_spec.md) reads like the traits should be increasing in scope depending on the impls, I tried to decouple them a bit to make them more additive and to clarify which trait is responsible for what.
Firstly, instead of requiring the `EvmWiring::Transaction` to be convertible to its RPC counterpart directly in the trait bound, I moved the fallible conversion down to the RpcSpec. While strictly less powerful (does not impl TryFrom anymore but also was not used) I feel that it makes it clear that the `RpcSpec` …
> [multi-chain]: Drive-by clarify the required traits in `ChainSpec` and decouple them a bit

- crates/edr_evm/src/blockchain/storage.rs
- crates/edr_evm/src/blockchain/storage/contiguous.rs
This was not included in the project by mistake, so this brings that back and adapts the code to compile again.
cc @Wodann since we talked about this on IM
> fix: Prevent contiguous blockchain storage from bitrotting

- book/src/02_development/06_style_guide.md
- book/src/SUMMARY.md
Proposal for adding guidelines around code style
> doc: add style guide

- .changeset/seven-dogs-decide.md
- crates/edr_napi/src/trace/error_inferrer.rs
- crates/edr_solidity/src/artifacts.rs
...and mimick what Hardhat does, i.e. catch an internal error (rather than unconditionally print a panic message) when we analyze a call trace with no jump destination.
@fvictorio this fixes the issues we caught when testing the Seaport repository.
> fix: Correctly handle optional solc output in the tracing engine

- .changeset/hungry-cats-enjoy.md
- crates/edr_provider/src/data.rs
- crates/edr_provider/src/time.rs
- crates/edr_provider/tests/issues/issue_588.rs
- crates/edr_provider/tests/issues/mod.rs
Closes #588
This uses a simple approach of first converting to `i128`, which we know will be lossless, to only then fallibly convert it to a smaller type of `i64`.
We do that for simplicity: one could convert a tuple of (sign, value) to shave some bytes and cycles but we would have to explicitly handle the case of `i64::MIN` (its absolute value is greater by 1 than i64::MAX), which would be a bit noisy, whereas not handling it and naively using a `if sign { -1 } else { 1 } * i64::try_from(value)...` would not fully handle that edge case.
I tested locally the reproduction steps from #588 and can both confirm that the error happens using the steps and the problem disappears after applying the fix here. Let me know if you feel that we should add a regression test and if so, how would you …
> fix: Allow block time offset to be negative

- Cargo.lock
- crates/edr_napi/Cargo.toml
This fixes an instance where we roundtrip a zero-length `Uint8Array` in JS code and violate the `slice::from_raw_parts` contract (checked in debug builds at run-time since Rust 1.78) because internally napi calls it with a null pointer, see https://github.com/napi-rs/napi-rs/pull/2258.
Found while running the test suite of https://github.com/ProjectOpenSea/seaport with local, most recent Hardhat+EDR.
This should unblock further testing and releasing a Hardhat version that uses the EDR-powered stack tracing.
> fix: Handle nullptr JS TypedArrays by bumping napi to 2.6.11

- crates/edr_napi/index.d.ts
- crates/edr_napi/package.json
- pnpm-lock.yaml
This should make the CI green again and fixes an oversight from #673 (shouldn't merge queue be blocked on that?), where I forgot to re-generate the new index.d.ts file after bumping the napi typings.
Since the change now adds the `declare` to the top-level functions, I figured we can just go all the way and do the same for the classes, which is already done by bumping @napi-rs/cli to 2.18.4 (outstanding; closes #621).
> fixup: Re-generate the index.d.ts file and bump @napi-rs/cli to 2.18.4

- crates/edr_napi/src/solidity_tests/config.rs
- crates/edr_solidity_tests/tests/it/core.rs
- crates/edr_solidity_tests/tests/it/helpers.rs
- crates/edr_solidity_tests/tests/testdata/cheats/Vm.sol
- crates/edr_solidity_tests/tests/testdata/default/core/ExecutionContext.t.sol
- crates/foundry/cheatcodes/assets/cheatcodes.json
- crates/foundry/cheatcodes/spec/src/lib.rs
- crates/foundry/cheatcodes/spec/src/vm.rs
- crates/foundry/cheatcodes/src/config.rs
- crates/foundry/cheatcodes/src/env.rs
- crates/foundry/cheatcodes/src/lib.rs
- js/integration-tests/solidity-tests/contracts/ContractEnvironment.t.sol
- js/integration-tests/solidity-tests/contracts/FuzzFixture.t.sol
- js/integration-tests/solidity-tests/test/unit.ts
Foundry has an `isContext` [cheatcode](https://github.com/foundry-rs/foundry/pull/7377) that tells you which `forge` command was used to execute the Solidity code (e.g. `forge test` or `forge coverage` or `forge script`). 
I adapted the `isContext` cheatcode for EDR by renaming the context enum from `ForgeContext` to `ExecutionContext` and removed the scripting related variants.
The Foundry code assumes that Solidity code is ran via the `forge` CLI and that the execution context is set based on the subcommand once per process. This doesn't make sense for us, since EDR provides Solidity tests as a library, so I changed this to getting the execution context as a config value in the cheatcode implementation.
I changed the representation of the execution context in the Rust code. I split the …
> refactor: adapt `isContext` cheatcode

- .changeset/famous-eggs-buy.md
- crates/edr_napi/src/trace/error_inferrer.rs
This was a mistake done when porting; the original code is correct: https://github.com/NomicFoundation/hardhat/blob/f93c4478dbe366ecbe13c793e630ec761e98ee6e/packages/hardhat-core/src/internal/hardhat-network/stack-traces/error-inferrer.ts#L1700
I've tried to scan the both ports and couldn't find any more obvious bugs; hopefully I didn't miss anything.
@fvictorio this fixes the latest OpenZeppelin issue that we caught.
> fix: Use correct bytecode in proxy error propagation check

- .changeset/dirty-phones-vanish.md
- crates/edr_solidity/src/source_map.rs
This fixes the adding unmapped instruction logic started from a misaligned opcode, i.e. in the middle of a PUSHx opcode. The bug was present in the original code but it did not verify the opcode for correctness, which is why we're only seeing it now.
@fvictorio this fixes the Chainlink's issue that's been reported lately.
> fix: Only add unmapped instructions at the opcode boundary

- .github/workflows/edr-npm-release.yml
- .syncpackrc.js
- crates/edr_napi/index.js
- crates/edr_napi/npm/darwin-arm64/package.json
- crates/edr_napi/npm/darwin-x64/package.json
- crates/edr_napi/npm/linux-arm64-gnu/package.json
- crates/edr_napi/npm/linux-arm64-musl/package.json
- crates/edr_napi/npm/linux-x64-gnu/package.json
- crates/edr_napi/npm/linux-x64-musl/package.json
- crates/edr_napi/npm/win32-x64-msvc/package.json
- crates/edr_napi/package.json
- crates/edr_napi/scripts/prepublish.sh
- crates/tools/js/benchmark/package.json
- crates/tools/js/benchmark/test/test-local-edr.ts
- hardhat-tests/package.json
- hardhat-tests/test/edr-override.ts
- js/helpers/package.json
- js/helpers/src/index.ts
- js/integration-tests/solidity-tests/package.json
- js/integration-tests/solidity-tests/test/fuzz.ts
- js/integration-tests/solidity-tests/test/testContext.ts
- package.json
- pnpm-lock.yaml
This PR mainly replaces `@nomicfoundation/edr` with `@ignored/edr` wherever it makes sense. Besides that:
- It uses the `IGNORED_ORG_NPM_TOKEN` secret for the release workflow.
- It uses optional dependencies to publish, like we used to do. This simplifies things locally, at least until we actually make a release in npm. Notice that the comment that explains this mentions `@ignored`; my hope here is that we'll remember to do this when we grep `@ignored` to remove all occurrences in the project.
> chore: use @ignored npm namespace

- .github/workflows/edr-benchmark-feat-solidity-tests.yml
- .github/workflows/edr-benchmark.yml
- crates/tools/js/benchmark/src/solidity-tests.ts
This PR adds automated regression checks for the JS Solidity test runner. The setup is similar to how the RPC benchmark that benchmarks Hardhat Node-style workloads works.
The benchmark runs the test harness of `forge-std`. This has two advantages:
- Largest coverage of cheatcodes in a single test harness which is helpful to catch regressions in all features.
- Makes sure our implementation works with `forge-std` which we intend to use.
The disadvantage is that `forge-std` is not representative of how users are writing Solidity tests. But this is not a concern as long as we’re not using the benchmark to guide optimizations, only to catch regressions.
There are multiple benchmark scenarios. The first one is called `Total` which measures the entire test harness execution of the `forge-std` …
> ci: solidity test benchmarks

- crates/edr_napi/src/trace/error_inferrer.rs
Replaces `unwrap`s with `expect`s to make it easier to debug Solidity Stack trace code.
> refactor: use expect instead of unwrap

- Cargo.toml
I changed from `"crates/*"` in the workspace Cargo.toml to listing crates one-by-one, because I kept running into errors as I was switching back and forth between branches with different crates.
> misc: make crate names explicit

- .changeset/mighty-turtles-wait.md
- Cargo.lock
- crates/edr_defaults/Cargo.toml
- crates/edr_defaults/src/lib.rs
- crates/edr_evm/src/blockchain/remote.rs
See https://github.com/NomicFoundation/edr/issues/696 for rationale. Supersedes https://github.com/NomicFoundation/edr/pull/695.
Relevant Hardhat issues:
- https://github.com/NomicFoundation/hardhat/discussions/5814
- https://github.com/NomicFoundation/hardhat/issues/5816
> fix: total difficulty fallback for remote blocks

- crates/edr_napi/src/solidity_tests.rs
- crates/edr_napi/src/solidity_tests/runner.rs
- crates/edr_napi/test/solidity-tests.ts
Make sure the config error callback is called with an error if an invalid artifact is provided. Partially fixes https://github.com/NomicFoundation/edr/issues/700
> fix: report config error on invalid artifact

- crates/edr_solidity_tests/src/multi_runner.rs
- crates/edr_solidity_tests/src/runner.rs
- crates/edr_solidity_tests/tests/it/fork.rs
- js/integration-tests/solidity-tests/contracts/Empty.t.sol
- js/integration-tests/solidity-tests/test/unit.ts
Make sure we return an empty test suite result for empty test suites. 
The fix changes the semantics of the `TestFilter` slightly, hence the need for the change to `crates/edr_solidity_tests/tests/it/fork.rs`, but since the `TestFilter` isn't exposed (it's only used in integration tests), I think this is ok. 
The change in semantics is that previously we only returned results for a test suite if the test name filter also matched at least one test name in the test suite. Now we return an empty result instead if the path filter and suite name filter match, but the test name filter doesn't match.
Fixes https://github.com/NomicFoundation/edr/issues/702
> fix: return empty result for empty test suite

- Cargo.lock
- Cargo.toml
- crates/edr_solidity_tests/tests/it/fork.rs
- crates/edr_solidity_tests/tests/it/helpers.rs
- crates/edr_solidity_tests/tests/testdata/default/cheats/LastCallGas.t.sol
- crates/foundry/cheatcodes/assets/cheatcodes.json
- crates/foundry/cheatcodes/spec/src/vm.rs
- crates/foundry/cheatcodes/src/evm.rs
- crates/foundry/cheatcodes/src/evm/mapping.rs
- crates/foundry/cheatcodes/src/evm/mock.rs
- crates/foundry/cheatcodes/src/inspector.rs
- crates/foundry/evm/core/src/backend/mod.rs
- crates/foundry/evm/core/src/fork/backend.rs
- crates/foundry/evm/core/src/fork/cache.rs
- crates/foundry/evm/core/src/ic.rs
- crates/foundry/evm/core/src/utils.rs
- crates/foundry/evm/coverage/src/anchors.rs
- crates/foundry/evm/coverage/src/inspector.rs
- crates/foundry/evm/evm/src/executors/mod.rs
- crates/foundry/evm/evm/src/inspectors/logs.rs
- crates/foundry/evm/evm/src/inspectors/stack.rs
- crates/foundry/evm/fuzz/src/inspector.rs
- crates/foundry/evm/fuzz/src/strategies/state.rs
Bump the forked Foundry crates for the Solidity tests feature to use REVM 9. 
Based on https://github.com/foundry-rs/foundry/pull/7934. There was one additional change required: specifying the Cancun hardfork for the Rust integration tests, as they used the default version and in Revm 9 that is Prague which caused problems. (The JS interface specifies Cancun explicitly.)
> chore: upgrade soltest crates to Revm 9

- crates/edr_solidity_tests/tests/it/helpers.rs
- crates/edr_solidity_tests/tests/testdata/default/cheats/Fork.t.sol
- crates/edr_solidity_tests/tests/testdata/default/cheats/Fork2.t.sol
- crates/edr_solidity_tests/tests/testdata/default/cheats/RpcUrls.t.sol
- crates/edr_solidity_tests/tests/testdata/default/fork/ForkSame_1.t.sol
- crates/edr_solidity_tests/tests/testdata/default/fork/ForkSame_2.t.sol
- crates/edr_solidity_tests/tests/testdata/default/fork/Transact.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue2623.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue2629.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue2723.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue3077.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue3110.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue3119.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue3192.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue3220.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue3653.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue3703.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue4586.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue4640.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue5929.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue5935.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue6032.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue6538.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue6616.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue6759.t.sol
- crates/edr_solidity_tests/tests/testdata/default/repros/Issue7481.t.sol
- crates/edr_test_utils/src/env.rs
I have limited experience in this area, but I have taken the following steps:
1. Examined how it is done in the Foundry repository. 
3. Collected hardcoded URLs in the Solidity file. 
3. Added names based on the URLs and referenced them in Solidity.
4. Ran `cargo test`.
The hardcoded URLs in the file `crates/edr_solidity_tests/tests/testdata/default/cheats/RpcUrls.t.sol` `crates/tools/js/benchmark/src/solidity-tests.ts`  have not been modified.
#643
> chore: update fork url

- crates/tools/js/benchmark/package.json
- crates/tools/js/benchmark/src/solidity-tests.ts
- pnpm-lock.yaml
Get  network config from foundry.toml to replace hardcoded URLs.
Add [smol-toml](https://github.com/squirrelchat/smol-toml) package to parse the toml config
resolve #709
> chore: get network config from foundry.toml

- .github/workflows/edr-ci.yml
- crates/edr_optimism/Cargo.toml
- crates/edr_optimism/src/hardfork.rs
- crates/edr_optimism/tests/provider.rs
- crates/edr_provider/Cargo.toml
- crates/edr_provider/src/data.rs
- crates/edr_provider/src/requests/eth/gas.rs
- crates/edr_provider/src/requests/eth/transactions.rs
- crates/edr_provider/src/requests/resolve.rs
- crates/edr_provider/src/test_utils.rs
This fixes an incorrect chain ID for the OP Sepolia testnet.
It also adds a test. To support this test, I needed to perform a small refactor to expose the `ProviderTestFixture` and make it chain-specific.
> fix: Optimism Sepolia hardfork

- crates/edr_optimism/src/transaction/request.rs
- crates/edr_optimism/tests/provider.rs
This fixes a merge error resulting in latest chain ID always being used for `eth_call` instead of using the chain ID at the block number.
> fix: chain ID at block number

- crates/edr_napi/src/context.rs
- crates/edr_napi/test/context.ts
- crates/edr_napi/test/helpers.ts
- crates/edr_napi/test/issues.ts
- crates/edr_napi/test/provider.ts
Previously we were only setting a default tracing subscriber for the current thread in `edr_napi` which precluded logs from other threads being collected.
With this change, the subscriber is set globally for all threads so that we can get tracing output when running JS tests, e.g. from `hardhat-tests`: `RUST_LOG=debug pnpm test`.
> chore: fix setting tracing subscriber

- .github/workflows/edr-npm-release.yml
GitHub runner deprecated macos-12 (see https://github.com/actions/runner-images/issues/10721). macos-13 is the latest image to still support x86.
> Update macos-12 to macos-13 (latest macos to still support intel).

- book/src/02_development/07_pnpm_patch.md
- book/src/SUMMARY.md
Adds an entry to the book explaining how to patch a `pnpm` dependency
> docs: add book entry about pnpm patch

- .github/workflows/edr-benchmark.yml
Reduce max items in performance chart for better visibility of recent changes.
https://nomic-foundation-automation.github.io/edr-benchmark-results/bench/
> ci: reduce max items in performance chart

- js/integration-tests/solidity-tests/contracts/ContractEnvironment.t.sol
- js/integration-tests/solidity-tests/contracts/EnvVar.t.sol
- js/integration-tests/solidity-tests/contracts/ForkCheatcode.t.sol
- js/integration-tests/solidity-tests/contracts/FuzzFixture.t.sol
- js/integration-tests/solidity-tests/contracts/Invariant.t.sol
- js/integration-tests/solidity-tests/contracts/IsolateTest.sol
- js/integration-tests/solidity-tests/contracts/Overflow.t.sol
- js/integration-tests/solidity-tests/hardhat.config.ts
- js/integration-tests/solidity-tests/package.json
- js/integration-tests/solidity-tests/test/unit.ts
- pnpm-lock.yaml
Switch to `forge-std` for Solidity test JS integration tests.
> test: switch to `forge-std` for JS integration tests

- crates/edr_evm/src/block/builder.rs
The operation
```
let drift = header.number - dao_hardfork_activation_block
```
underflows if for example `header.number` is 1 and `dao_hardfork_activation_block` is the actual hardfork activation (1_920_000). 
This panics in debug mode and wraps around in release mode silently. The wrapping doesn't cause any problems, because the subsequent check `drift <= DAO_FORCE_EXTRA_DATA_RANGE` is false if it wrapped around. 
Still, it's not great to have a panic here in debug mode, so I fixed it by refactoring the drift check. Since there is no user impact, I don't think we need a changelog item.
We haven't caught this before, because we run Hardhat integration tests in release mode.
> fix: dao hardfork activation check underflow

- .changeset/strange-boxes-shout.md
- Cargo.lock
- crates/edr_solidity/Cargo.toml
- crates/edr_solidity/benches/contracts_identifier.rs
- crates/edr_solidity/src/bytecode_trie.rs
- crates/edr_solidity/src/contracts_identifier.rs
- crates/edr_solidity/src/lib.rs
This PR fixes stack overflow on drop in the `BytecodeTrie` by eliminating one-way branching which produces very deep tries for large contracts. Care has been taken to preserve the implementation details of the previous implementation which the stack trace heuristics rely on.
I moved the `BytecodeTrie` to a separate module in [7bcb871](https://github.com/NomicFoundation/edr/pull/775/commits/7bcb8712fb70428a6184292a13100daccce06e51). The changes to eliminate one-way branching can be reviewed by reviewing [76840d8](https://github.com/NomicFoundation/edr/pull/775/commits/76840d88c77e6688f616f430f6b50ced1e85bd66).
I also added a [benchmark](https://github.com/NomicFoundation/edr/pull/775/files#diff-f3f8c0e043dcf722c2eb7c98f6ce432856efd6464495c6f54051985243bcdb34) for constructing the …
> fix: remove one way branching in bytecode trie

- crates/tools/js/benchmark/src/index.ts
We've improved a lot on the `seaport` and `uniswap` benchmark scenarios which causes variability resulting in false positive regression alerts. The variability is observable visually at: https://nomic-foundation-automation.github.io/edr-benchmark-results/bench/
This is a quick fix for the variability by bumping the number of iterations for these scenarios. A proper fix would be using a more robust statistic for the results, but this takes some time to test.
> ci: bump `seaport` and `uniswap` benchmark samples

- .changeset/popular-singers-sit.md
- crates/edr_napi/.cargo/config.toml
Fixes https://github.com/NomicFoundation/edr/issues/781
Tested locally on a fresh Windows install.
> fix: statically link Windows C runtime

- Cargo.lock
- crates/edr_solidity/src/solidity_stack_trace.rs
- crates/edr_solidity_tests/Cargo.toml
- crates/edr_solidity_tests/src/lib.rs
- crates/edr_solidity_tests/src/runner.rs
- crates/edr_solidity_tests/src/stack_trace.rs
- crates/edr_solidity_tests/tests/it/core.rs
- crates/edr_solidity_tests/tests/it/invariant.rs
- crates/foundry/evm/evm/Cargo.toml
- crates/foundry/evm/evm/src/executors/invariant/mod.rs
- crates/foundry/evm/evm/src/executors/invariant/replay.rs
- crates/foundry/evm/evm/src/executors/mod.rs
- crates/foundry/evm/evm/src/executors/stack_trace.rs
- js/helpers/package.json
- js/integration-tests/solidity-tests/contracts/FailingDeploy.t.sol
- js/integration-tests/solidity-tests/contracts/Invariant.t.sol
- js/integration-tests/solidity-tests/test/fuzz.ts
- js/integration-tests/solidity-tests/test/testContext.ts
- js/integration-tests/solidity-tests/test/unit.ts
Adds stack trace support by re-executing failed calls for
- deployment and setup for all types of tests
- invariant tests
Re-execution on deployment and setup is rather forward, but for invariant tests there are two things to consider:
1. Previously, we only did tracing on setup and deployment if the invariant test had a `setUp` method. It greatly simplifies re-execution if we always do tracing on setup and deployment if there are invariant tests. The performance decrease should be negligible, because most invariant test have a `setUp` method and since they tend to take longer, the overhead is amortized.
2.  The way the revert reason is returned for invariant tests is a bit weird in Foundry. Sometimes it's not returned even if there is a revert and when replaying a recorded invariant …
> feat: stack trace support for setup/deployment and invariant tests

- crates/edr_eth/src/eips/eip7702.rs
- crates/edr_eth/src/transaction/signed.rs
- crates/edr_evm/src/transaction.rs
- crates/edr_provider/src/requests/eth/transactions.rs
- crates/edr_provider/tests/integration/eip7702.rs
- crates/edr_rpc_eth/src/transaction.rs
This fixes two issues with EIP-7702 transactions:
- We were never parsing remote transactions to `transaction::Signed`, instead recognising them as EIP-155 transactions
- We weren't returning EIP-7702 properties from the JSON-RPC interface
> fix: return EIP-7702 properties for transactions

- .changeset/sour-coats-look.md
After discussing, we decided that the changes to the JSON-RPC should be a breaking change.
> misc: make EIP-7702 a breaking change

- CONTRIBUTING.md
For now just added guidelines on small PRs and airdrop farming based on Hardhat's [CONTRIBUTING](https://github.com/NomicFoundation/hardhat/blob/main/CONTRIBUTING.md). We should consider extending this with development guidelines on EDR (filed https://github.com/NomicFoundation/edr/issues/829).
> Add contributor guidelines for small PRs and airdrop farming

- Cargo.lock
- crates/foundry/cheatcodes/Cargo.toml
- crates/foundry/cheatcodes/src/inspector.rs
- js/integration-tests/solidity-tests/contracts/UnsupportedCheatcode.t.sol
- js/integration-tests/solidity-tests/package.json
- js/integration-tests/solidity-tests/test/unit.ts
- pnpm-lock.yaml
Adds better error messages when invoking unsupported cheatcodes. Previously we'd just return `"unknown selector 0xafc98040"`, now we return `"cheatcode 'broadcast()' is not supported"` instead.
In order to know if an unknown selector refers to an unsupported cheatcode, we have to have access to the latest cheatcode abi from the Foundry repo. I solved this by including the `foundry-cheatcodes-spec` package from the Foundry repo as a git dependency. This'll not work if we want to publish the `edr_solidity_tests` package on crates.io, but I think it's fine until then. The alternative would be to copy over the cheatcode abi from the Foundry repo, but that's more difficult to keep up-to-date.
No changeset needed, as we don't use changesets for the `feat/solidity-tests` branch.
> feat: error for unsupported cheatcodes

- crates/edr_napi/src/lib.rs
- crates/edr_napi/src/serde.rs
- crates/edr_napi/src/solidity_tests/config.rs
I added this while debugging something and it can be useful in the future as well for debugging as the arguments are too long to print.
> chore: add serialize for `SolidityTestRunnerConfigArgs` config

- .changeset/eight-otters-love.md
- .changeset/nine-wasps-promise.md
- crates/edr_napi/CHANGELOG.md
- crates/edr_napi/package.json
A branch intended to test a prerelease version of EDR before performing the release. This branch should be merged manually.
> edr-0.12.0-alpha.0

- crates/edr_solidity/src/linker.rs
While this is technically user-facing and produces a change in an output, I don't think it needs a changeset because it's very small and it only happens in a corner case (that we are going to fix anyway). So it's fine for this to be released whenever there's a release.
> chore: improve linking error message

- .changeset/lemon-pumas-walk.md
- Cargo.lock
- Cargo.toml
- crates/edr_eth/Cargo.toml
- crates/edr_evm/Cargo.toml
- crates/edr_generic/Cargo.toml
- crates/edr_instrument/Cargo.toml
- crates/edr_instrument/src/coverage.rs
- crates/edr_instrument/src/lib.rs
- crates/edr_napi/Cargo.toml
- crates/edr_napi/index.d.ts
- crates/edr_napi/index.js
- crates/edr_napi/src/instrument.rs
- crates/edr_napi/src/lib.rs
- crates/edr_napi/test/instrument.ts
- crates/edr_napi_core/Cargo.toml
- crates/edr_op/Cargo.toml
- crates/edr_provider/Cargo.toml
- crates/edr_rpc_client/Cargo.toml
- crates/edr_rpc_eth/Cargo.toml
- crates/edr_scenarios/Cargo.toml
- crates/edr_solidity/Cargo.toml
- crates/edr_test_utils/Cargo.toml
- crates/tools/Cargo.toml
- data/contracts/instrumentation.sol
This PR adds an API for instrumenting statement code coverage, based on [this research spike](https://github.com/NomicFoundation/hardhat-coverage-spike/blob/main/src/lib.rs).
Should be merged after #866!
> feat: add statement coverage instrumentation

- crates/edr_op/tests/integration/rpc.rs
We [previously removed](https://github.com/NomicFoundation/edr/pull/853) support for pre-Byzantium receipts from EDR, due to a change in archive nodes.
It seems that they're now also reporting the type of a transaction for pre-EIP-2718 receipts. I've inquired with Alchemy whether this is in fact the case.
Until then, the modification in this PR allows both cases to pass.
> test: allow transaction type for legacy receipts

- crates/edr_napi/index.d.ts
- crates/edr_napi/src/config.rs
- crates/edr_napi/src/instrument.rs
This PR adds detailed documentation for code coverage and instrumentation.
> doc: add code coverage documentation to API

- .changeset/poor-shirts-collect.md
- Cargo.lock
- Cargo.toml
- crates/edr_instrument/Cargo.toml
- crates/edr_instrument/src/coverage.rs
- crates/edr_napi/index.d.ts
- crates/edr_napi/src/instrument.rs
- crates/edr_napi/test/instrument.ts
Require specification of the coverage library path when adding coverage instrumentation.
> feat: require coverage library path to be specified

- crates/edr_napi/npm/darwin-arm64/package.json
- crates/edr_napi/npm/darwin-x64/package.json
- crates/edr_napi/npm/linux-arm64-gnu/package.json
- crates/edr_napi/npm/linux-arm64-musl/package.json
- crates/edr_napi/npm/linux-x64-gnu/package.json
- crates/edr_napi/npm/linux-x64-musl/package.json
- crates/edr_napi/npm/win32-x64-msvc/package.json
- crates/edr_napi/package.json
> **⚠️ This branch is intended to test the upcoming release and should be merged manually, to trigger the release**
This release contains the following changes:
- Deprecated `deleteSnapshot`, `deleteSnapshots`, `revertTo`, `revertToAndDelete`, and `snapshot` cheatcodes in favor of `deleteStateSnapshot`, `deleteStateSnapshots`, `revertToState`, `revertToStateAndDelete`, and `snapshotState`
> edr-0.10.0-alpha.5

- crates/tools/js/benchmark/src/solidity-tests.ts
While merging several PRs into `feat/solidity-tests`, I've had to re-run the soltest benchmark  job numerous times due to variability in the small test suites, which take ~20ms (e.g. [CI log](https://github.com/NomicFoundation/edr/actions/runs/15262322988/attempts/2?pr=917)).
This PR increases the number of samples for both of these test suites to 45, which would still total to less than 1 second per test suite.
Compared to re-running the full 16-minute job and potentially waiting for or delaying other benchmark runs in the queue, this is a more than acceptable trade-off for me.
> ci: increase benchmark runs to reduce CI false negatives

- book/src/01_getting_started/01_setup.md
This PR removes the setup instructions using Homebrew on macOS since they are no longer applicable (Brewfile is no longer present in the repo).
> docs: remove macOS brew setup instructions

- crates/edr_eth/src/block.rs
This PR adds a new test for RLP encoding and block hash on a Prague block. The Prague update introduced the `requests_hash` field as part of the block header in #813 .
> test: add test for RLP encoding Prague block header

- .github/workflows/edr-ci.yml
We've identified potential issues with the use of GitHub Actions cache for RPC requests.
The cache at a key is immutable (except for evictions), once a cache key is written to it won't be updated. This is an issue for the RPC requests cache because the set of RPC requests can change as tests are added or depend on the OS (some tests are OS-specific). This PR fixes that by hashing the cache contents and using that in the key. Since the contents aren't known until the end of the run we always restore from the most recently created cache via `restore-keys`.
~Another issue is that caches are by default not shared across OSs. So the Windows run is not sharing a cache with the Ubuntu and macOS runs. This PR enables cross-OS caching.~ &rarr; Disabling this since some tests are OS-specific.
> chore: fix workflow caching of rpc requests

- .changeset/rotten-vans-divide.md
- crates/edr_napi/index.d.ts
- crates/edr_napi/src/cast.rs
- crates/edr_napi/src/serde.rs
- crates/edr_napi/src/solidity_tests/config.rs
- crates/edr_napi/src/solidity_tests/test_results.rs
This PR replaces all occurrences of `Buffer` with `Uint8Array` in Solidity tests interface.
I have also bumped up the minor version since this is a breaking change.
closes #946
> chore: replace Buffer with Uint8Array in Solidity tests interface

- .changeset/spicy-cameras-fix.md
- crates/edr_solidity/src/error_inferrer.rs
- hardhat-tests/test/internal/hardhat-network/stack-traces/compilation.ts
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/call-message/modifier-private-method/c.sol
- hardhat-tests/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/call-message/modifier-private-method/test.json
Fixes a panic on stack trace generation for a receive function with a modifier that calls another method.
Fixes https://github.com/NomicFoundation/edr/issues/894
> fix: avoid panic on stack trace for receive with modifier

- crates/edr_provider/src/data.rs
This PR removes unnecessary cloning of custom precompiles for `eth_sendTransaction` flow, added in #973
> chore: remove unnecessary clones for custom precompiles

- book/src/01_getting_started/01_setup.md
Adds a note to the book to make sure the dev container has enough memory. Increasing from the default 8GB on macOS to 16GB solved most of the Rust language server crashes for me. Also adds a setting that speeds up rust-analyzer checks significantly by ignoring expanding on napi proc-macro.
> docs: add setup notes to improve VS Code experience

- .github/codecov.yml
#982 did not disable the right thing: [status checks](https://docs.codecov.com/docs/commit-status) are not the same as [GitHub checks](https://docs.codecov.com/docs/github-checks).
Note Codecov should continue to post a comment in PRs.
> chore: disable Codecov statuses

- .changeset/slow-houses-call.md
- crates/edr_napi/src/trace/library_utils.rs
- crates/edr_solidity/src/build_model.rs
- crates/edr_solidity/src/bytecode_trie.rs
- crates/edr_solidity/src/compiler.rs
- crates/edr_solidity/src/error_inferrer.rs
- crates/edr_solidity/src/library_utils.rs
- crates/edr_solidity/src/mapped_inline_internal_functions_heuristics.rs
- crates/edr_solidity/src/nested_tracer.rs
- crates/edr_solidity/src/solidity_tracer.rs
- crates/edr_solidity/src/source_map.rs
Cherry-picked https://github.com/NomicFoundation/edr/pull/983 for release in HH2
There were some merge conflicts related to the generic halt reason in `main` that I resolved mechanically.
Stacked on top https://github.com/NomicFoundation/edr/pull/987
> refactor: use errors instead of panics for invariant violations (#983)

- .changeset/flat-books-retire.md
- .changeset/slow-houses-call.md
- .changeset/spicy-cameras-fix.md
- crates/edr_napi/CHANGELOG.md
- crates/edr_napi/npm/darwin-arm64/package.json
- crates/edr_napi/npm/darwin-x64/package.json
- crates/edr_napi/npm/linux-arm64-gnu/package.json
- crates/edr_napi/npm/linux-arm64-musl/package.json
- crates/edr_napi/npm/linux-x64-gnu/package.json
- crates/edr_napi/npm/linux-x64-musl/package.json
- crates/edr_napi/npm/win32-x64-msvc/package.json
- crates/edr_napi/package.json
- 1ac9b2e4: Fixed custom precompiles not being applied in `eth_sendTransaction`. This enables RIP-7212 support in transactions.
- 7e12f64: Fixed panic on stack trace generation for receive function with modifier that calls another method. https://github.com/NomicFoundation/edr/issues/894
- 5861ad6: Turned panics during stack trace generation due to invalid assumptions into errors.
> edr-0.11.3

- crates/edr_evm/src/block/builder.rs
- crates/edr_evm/src/miner.rs
- crates/edr_provider/src/test_utils.rs
This PR improves #976 by moving custom precompiles to the BlockBuilder, which removes the possibility of using different precompiles for different transactions.
The hh2 branch version of #995
> chore: move custom precompiles to BlockBuilder

- .devcontainer/devcontainer.json
Updates devcontainer node version to 22. Some parts of the code (HH3 project in `js/integration_tests/solidity_tests`) require node v22 to run.
> chore: update node to v22 in devcontainer

- .github/scripts/cargo-doc.sh
We have an issue currently where Foundry source files have doc warnings.
This PR removes those warnings by adding `RUSTDOCFLAGS="-A warnings"`. I also changed the script a little to run a single `cargo doc` command per group rather than one per crate (this may improve parallelism?), but let me know if you prefer the previous version.
> chore: improve docs script and remove warnings

- .changeset/tender-pillows-grab.md
- crates/edr_napi/index.d.ts
- crates/edr_napi/src/solidity_tests/test_results.rs
- crates/tools/js/benchmark/src/solidity-tests.ts
Report Solidity test execution times in nanoseconds instead of milliseconds. This is needed for accurate comparisions with forge which reports nanoseconds when running `forge test --json`.
> feat: test execution time in nanoseconds

- .changeset/stupid-dryers-know.md
- crates/edr_napi/index.d.ts
- crates/edr_napi/index.js
- crates/edr_napi/src/solidity_tests/config.rs
- crates/foundry/cheatcodes/src/config.rs
- crates/foundry/cheatcodes/src/inspector.rs
- js/integration-tests/solidity-tests/test-contracts/InternalExpectRevert.t.sol
- js/integration-tests/solidity-tests/test/unit.ts
Add `allowInternalExpectRevert` global config option which is needed by the [Uniswap v4 ](https://github.com/Uniswap/v4-core/blob/59d3ecf53afa9264a16bba0e38f4c5d2231f80bc/foundry.toml#L10) and [prb-math](https://github.com/PaulRBerg/prb-math/blob/aad73cfc6cdc2c9b660199b5b1e9db391ea48640/foundry.toml#L4) repos.
Only JS tests, no Rust tests as this will be tested once on the Rust side once we have inline config option support, and the JS tests give enough confidence until then.
> feat: add `allowInternalExpectRevert` config option

- .github/workflows/release.yml
The release workflow is [failing on main](https://github.com/NomicFoundation/edr/actions/runs/16509302271/job/46687723525) after https://github.com/NomicFoundation/edr/pull/1020.
When there is no new release, `[ -n "$VERSION" ] || exit 1` is exiting the workflow with an error, which is not what we want. This removes that early error and just continues. `changesets/action` won't open a PR.
> chore/fix: release workflow early error

- .github/workflows/release.yml
It appears that Changesets is adding any files in the repository in its versioning commit, as seen in https://github.com/NomicFoundation/edr/pull/1024/commits/6f1288d7e40472e5edf5c02d780f5c5780f89216. This moves the temporary file to a temporary directory.
> chore/fix: remove temp file from changesets PR

- crates/tools/js/benchmark/src/solidity-tests.ts
Following https://github.com/NomicFoundation/edr/pull/1012, Solidity test benchmark run times [increased](https://github.com/NomicFoundation/edr/actions/runs/16680238634/job/47217929068?pr=1042) to over an hour. The culprits are:
- `[TOTAL_NAME]` increased from 5 -> 25 (this task takes about 70 seconds)
- `StdStorageTest` increased from 5 -> 25 (this task takes about 69 seconds)
To the best of my knowledge, these two tests never caused false positives, so I propose returning them to their original sample count.
> ci: reduce benchmark time by 80%

- crates/edr_napi/test/mock.ts
When my devcontainer was short on memory, I ran into a problem with the "issue 543" TS test "freezing" because the system would start writing RAM to disk and take forever.
By reducing the memory usage by 40%, we're still causing a crash in `JSON.stringify` but minimising the time & memory resources used.
I also lowered the timeout, as the test now runs quicker.
> test: reduce memory consumption of issue 543 test by 40%

- .github/workflows/release.yml
The commit and PR created by the Changesets bot doesn't trigger any checks if we use the built-in `secrets.GITHUB_TOKEN`. This is to prevent a loop of workflow triggers. The only way around it is to use a different token. We will need to configure it in repo secrets later.
> chore: use different token for Changesets PRs

- js/helpers/src/index.ts
We are seeing integration tests fail after a change in #1055.
I was no longer able to reproduce it locally with this fix.
> chore: fix race condition in integration tests

- crates/tools/js/benchmark/patches/forge-std.patch
- crates/tools/js/benchmark/patches/morpho-blue.patch
- crates/tools/js/benchmark/patches/prb-math.patch
- crates/tools/js/benchmark/patches/solady.patch
- crates/tools/js/benchmark/patches/uniswap-v4-core.patch
- crates/tools/js/benchmark/src/solidity-tests.ts
- crates/tools/js/benchmark/test/test-solidity-tests.ts
Includes two commits with improvements for the Forge comparison benchmark:
- [Improve forge duration parsing](https://github.com/NomicFoundation/edr/commit/3d166a7ad2037e0ba1d52ca97030545d36975d04)
- handle more types of `forge` duration strings/structs
- [Improve patches](https://github.com/NomicFoundation/edr/commit/27505186b021aa7927824350e7932c74f924a300)
- Use inline tables for fuzz/invariant configs for consistencyt
- Always prefix fuzz/invariant seed with 0x to make sure it's interpreted as hex by both tools
- Add missing `bytecodeHash: "none"` configs to HH3 config
- Fix missing fuzz seed in `morph-blue`
- Fix silently failing fuzz seed config in `prb-math`
> fix: forge comparison benchmark improvements

- crates/tools/js/benchmark/README.md
Add docs on updating patch files for the `pnpm compareForge` command.
> docs: add docs on updating patches

- .changeset/hungry-beans-agree.md
- crates/edr_provider/src/data.rs
- crates/edr_provider/src/requests/eth/gas.rs
- crates/edr_provider/src/requests/methods.rs
- crates/edr_provider/tests/integration/eth_request_serialization.rs
- crates/edr_rpc_client/src/cache/key.rs
- crates/edr_rpc_eth/src/cacheable_method_invocation.rs
- crates/edr_rpc_eth/src/client.rs
- crates/edr_rpc_eth/src/request_methods.rs
- hardhat-tests/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
- hardhat-tests/test/internal/hardhat-network/provider/modules/eth/methods/feeHistory.ts
[Ethereum JSON-RPC specifies](https://ethereum.github.io/execution-apis/api-documentation/) that all `eth_feeHistory` method parameters are required
Before these changes, the third parameter `rewardPercentiles` was optional in EDR. This was probably because [Alchemy documentation](https://www.alchemy.com/docs/node/ethereum/ethereum-api-endpoints/eth-fee-history) states that the parameter is optional - even if now it's rejecting the requests that do specify it
- Change rpc `eth_feeHistory` method definition to receive a `Vec<f64>` instead of an `Option<Vec<f64>>`
- Bonus track: [fixed ts type check failure](https://github.com/NomicFoundation/edr/commit/e3255dbe47df1f2464dac9c1b5584a6258ec5f8e)
> fix json-rpc `eth_feeHistory` method

- .github/dependabot.yml
- rust-toolchain
- scripts/setup.sh
Dependabot silently stopped working in our repo a long time ago (likely while we were still part of the Hardhat repo), when our `rust-toolchain` file format was deprecated:
This PR updates the file to the supported TOML format.
I also update the dependabot PR prefix to `build` to align with EDR's usage of the [conventional commit standard](https://www.conventionalcommits.org/en/v1.0.0/).
> build: update deprecated toolchain file to toml format

- .github/workflows/check-changeset-added.yml
- .github/workflows/edr-ci.yml
- .github/workflows/edr-npm-release.yml
- .github/workflows/hardhat-tests.yml
- .github/workflows/lock.yml
- .github/workflows/mdbook.yml
- .github/workflows/release.yml
- .github/workflows/test-recent-mainnet-block.yml
- .github/workflows/test-recent-optimism-block.yml
Using `latest` tags is a bad practice that can lead to unexpected changes and opens the door to security risks.
This PR updates CI jobs to use pinned versions of ubuntu, macos and windows. The version mapping was done considering [this](https://github.com/actions/runner-images/blob/41a7cee3c1afb1b3aad170ffae8d85bf262db862/README.md) is the current github runner-images documentation
I also updated jobs that were running in `ubuntu-22.04` to `ubuntu-24.04`
> chore: use os pinned versions in CI workflows 
